### PR TITLE
Cesride-wasm integration example e2e

### PR DESCRIPTION
**Pull request by daidoji**
This is a draft PR representing an e2e integration with cesride-wasm that corresponds with this PR in cesride:
https://github.com/WebOfTrust/cesride/pull/155

It uses the dater implementation from cesride-wasm to execute tests in signify-ts that correspond to the test_dater() tests in keripy that have been transcribed into jest.

Note: todos are due to deviations from keripy/signify-ts calling conventions and the current cesride implementation.  Also for future work is getting javascript options objects and destructuring to work so there's a better calling convention than `new Dater(dts, undefined, undefined, ...`

### CODE REVIEW

**Comment by daidoji** [comment]
_Note: Tests don't pass because I didn't work out the dependency issue on cesride-wasm._

**Comment by pfeairheller** [comment]
What's the intention of this PR?  Perhaps this work would be better on a fork if you just want a place to show how it _could_ work.

**Comment by daidoji** [comment]
@pfeairheller oh sorry, the intention was to demonstrate that cesride-wasm could be imported into signify-ts and would pass a unit test of js code proving interoperability.  I'm not sure if I have the ability to create a branch on this repo but that would be fine by me if one was created and I can push this there.

**Comment by daidoji** [comment]
Closed.  Implementation exists on daidoji/signify-ts if future generations are interested.

**Pull request closed without merging**
