### PR TITLE
use named imports from mathjs to reduce bundle size

### LINKED ISSUE #226: Excessive bundling size due to importing entire math.js library
See instructions here: https://mathjs.org/docs/custom_bundling.html#bundle-size

I did some testing and you can reduce the mathjs bundle contribution from ~500kb to ~80kb. By using the named exports, you can enable tree-shaking.

# Before:

```
// math.ts
import { create, all } from "mathjs"

const math = create(all)
export const math;

// tholder.ts
import math from "../../math.ts"
```

[meta.json](https://github.com/WebOfTrust/signify-ts/files/14402750/meta.json)
image

# After:

```
//tholder.ts
import { fraction, sum, format } from "mathjs";
```

[meta.json](https://github.com/WebOfTrust/signify-ts/files/14402760/meta.json)
image

You can upload the meta.json files to https://esbuild.github.io/analyze/ yourself to explore.

The meta.json files are generated by esbuild

```
npx esbuild --bundle src/index.ts --metafile=meta.json --outfile=out.js --platform=node --minify --analyze
```

### PR DESCRIPTION
**Pull request by lenkan**
Closes #226

### CODE REVIEW

**Review by rodolfomiranda — APPROVED** [review]
LGTM

**Review by rodolfomiranda — APPROVED** [review]

**Review by rodolfomiranda — APPROVED** [review]
This PR looks good to me

**Comment by m00sey** [comment]
@lenkan  you should be able to merge your own.

i do not use signify-ts it would be good to find someone to replace me

**Review by m00sey — APPROVED** [review]

**Comment by rodolfomiranda** [comment]
> i do not use signify-ts it would be good to find someone to replace me

I don't know why my approval didn't work

**Comment by lenkan** [comment]
> @lenkan you should be able to merge your own.
> 
> i do not use signify-ts it would be good to find someone to replace me

@m00sey  I still needed an approval from another reviewer with write access. Previously, @rodolfomiranda could approve, but it does not seem to be the case anymore. Does he not have write access anymore?

**Pull request merged**
