### PR TITLE
Incept salty managed keys and post to KERIA

### PR DESCRIPTION
**Pull request by rodolfomiranda**
Still pending:
- [x] passing of `...kargs`
- [x] improve `identifiers.create` method when arguments are `null`

### CODE REVIEW

**Comment by AlexAndrei98** [comment]
Looks like the Manager is breaking the Habery. Do we even need Habery? Otherwise it looks good to me

**Comment by rodolfomiranda** [comment]
> Looks like the Manager is breaking the Habery. Do we even need Habery? Otherwise it looks good to me

It's not using habery at all. Where it breaks?

**Comment by rodolfomiranda** [comment]
I found the error and fixed. Will be available in next commit

**Comment by rodolfomiranda** [comment]
Fixed some errors and added rotation

**Comment by AlexAndrei98** [comment]
tested and it work

**Pull request merged**
