### PR TITLE
Add Randy and Group AIDs

### PR DESCRIPTION
**Pull request by rodolfomiranda**

### CODE REVIEW

**Comment by rodolfomiranda** [comment]
Group AIDs also added

**Comment by AlexAndrei98** [comment]
Is there any way to test group aids in the UI?

**Comment by rodolfomiranda** [comment]
> Is there any way to test group aids in the UI?

no yet ;). It was implemented but not tested. I'm thinking to replicate the integration test that are part of `signifypy`

**Review by AlexAndrei98 — APPROVED** [review]
LGTM

**Pull request merged**
